<!-- <script src="{{ asset('codemirror/codemirror.js') }}"></script> -->
<script src="{{ asset('codemirror/addon/comment/comment.js') }}"></script>
<script src="{{ asset('codemirror/addon/lint/lint.js') }}"></script>
<script src="{{ asset('codemirror/addon/hint/show-hint.js') }}"></script>
<script src="{{ asset('codemirror/addon/fold/foldcode.js') }}"></script>
<script src="{{ asset('codemirror/addon/fold/foldgutter.js') }}"></script>
<script src="{{ asset('codemirror/grammars/css.js') }}"></script>
<script src="{{ asset('codemirror/grammars/htmlmixed.js') }}"></script>
<script src="{{ asset('codemirror/grammars/javascript.js') }}"></script>
<script src="{{ asset('codemirror/codemirror_grammar.min.js') }}"></script>
<script src="{{ asset('codemirror/addon/mode/xml.js') }}"></script>
<script src="{{ asset('codemirror/addon/mode/htmlmixed.js') }}"></script>
<script src="{{ asset('codemirror/addon/mode/css.js') }}"></script>
<script src="{{ asset('codemirror/addon/mode/javascript.js') }}"></script>
<script src="{{ asset('js/demo.js') }}"></script>
<!-- <script src="{{ asset('js/jquery.expect.js') }}"></script>
<script src="{{ asset('js/expect.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script> -->
